### PR TITLE
react-native compatibility

### PR DESCRIPTION
**Pull request by evansiroky**
isomorphic-fetch is not needed and causes an error if it is loaded in
the react-native environment

### CODE REVIEW

**Comment by StephanGeorg** [comment]
Hi @evansiroky. Thanks for the PR. I read about the issue. Maybe I switch to fetch-everywhere instead of isomorphic-fetch. What you think?

**Comment by evansiroky** [comment]
That should work fine I think.

**Comment by StephanGeorg** [comment]
Fixed by replacing isomorphic-fetch with fetch-everywhere in https://github.com/StephanGeorg/geocoder-arcgis/commit/2e17dd9df927739b172e9dc00cf4fb3b2d295f05.

Thanks for the hint and please confirm it.

**Comment by evansiroky** [comment]
Works great!  Thanks!

**Pull request closed without merging**
